// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package custom_types

type Block struct {
	Created *int     `json:"Created"`
	From    *string  `json:"From"`
	To      *string  `json:"To"`
	Value   *float64 `json:"Value"`
}
