start_timeout: 20s
stop_timeout: 20s

modules:
  modules:
    - stacking
#    - bank
#    - gov
#    - auth
#    - mint
#    - slashing
#    - distribution
#    - core

clickhouse:
  dsn: "clickhouse://default:@localhost:9000/spacebox"
  migrations_path: "adapter/clickhouse/migrations"
  auto_migrate: true

broker:
  address: "localhost"
  group_id: "myGroup"
  auto_offset_reset: "earliest"
